name: 'Build'

on: [pull_request]

jobs:
  build:
    name: 'Build'
    strategy:
      matrix:
        java: [ '8', '11', '13', '14' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: 'Cache Maven packages'
        uses: actions/cache@v2.1.4
        with:
          path: '~/.m2'
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: 'Run mvn verify'
        run: 'mvn --batch-mode clean verify -DskipUTs=false -DskipITs=true'
