name: 'Publish'

on:
  release:
    types: [created]

jobs:
  publish_package:
    name: 'Publish'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Set up GPG secret key'
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: 'Publish to Maven Central Repository'
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Prelease \
            -DskipTests=true \
            -DskipITs=true \
            -Dgpg.keyname=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }} \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            clean deploy